mysql:
  host: "mysql"
  port: 3306
  username: "root"
  password: "mysql123456"
  dbname: "music"
  charset: "utf8mb4"
  parseTime: true
  loc: "Local"

minio:
  endpoint: "minio:9000"
  rootUser: "minioadmin"
  rootPassword: "minioadminpassword"
  useSSL: false

redis:
  host: "redis"
  port: 6379
  password: ""
  db: 0