version: '3.8'

services:
  app:
    image: go-music
    container_name: music-server
    ports:
      - "8888:8888"  # 映射应用端口
    depends_on:
      - db
      - redis
      - minio
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - MINIO_ENDPOINT=minio:9000
      - MINIO_ACCESS_KEY=minioadmin
      - MINIO_SECRET_KEY=minioadminpassword
    networks:
      - app_network

  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: mysql123456
    ports:
      - "3306:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql
    networks:
      - app_network

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app_network

  minio:
    image: minio/minio
    container_name: minio
    command: server /data
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadminpassword
    ports:
      - "9000:9000"
    volumes:
      - ./minio_data:/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
